baseurl: ""
# markdown: kramdown
# kramdown:
#   parse_block_html: true
#   hard_wrap: false
nav:
  - DeviCat: /devicat
  - CandiCat: /candicat
  - Discord: https://discord.com/invite/devicat
  - Events: /events
  - Newsletter: /newsletter
  - Portfolio:
      - Art: /gallery
      - Catalog: /catalog
  - Shop: https://devicat-shop.fourthwall.com
  
excerpt_separator: <!--card-->