baseurl: ""
# markdown: kramdown
# kramdown:
#   parse_block_html: true
#   hard_wrap: false
nav:
  - DeviCat: /devicat
  - CandiCat: /candicat
  - Discord: https://discord.com/invite/devicat
  - Events: /events
  - Newsletter: /newsletter
  - Portfolio:
      - Art: /gallery
      - Catalog: /catalog
  - Shop: 
        - Cross-Stitch: https://sakidesjardins.shop/products/devicat-candicat-cross-stitch-pattern-trio-kawaii-x-stitch-pdf-cute-hand-drawn-anime-cat-design
        - Diamond Art Club: https://www.amazon.ca/DIAMOND-ART-CLUB-Painting-Beginners/dp/B0F4M34J2X?crid=24O6L13VWPQNO&dib=eyJ2IjoiMSJ9.oisgK_1NLCeBpdXI3Jj8v5up7S40FTIfm30ckYsuOWKx8B7X0-W2z9wAAmWzaD5hAPgAJl9RXECUsPUduVqUKsPx09x2ATS3DziOlUodBFDmFOndn90CoWX1Jfzv1Y9YcfQckiqP0sgDTMK88nPFa39IN-JSPacsAorQe4TdOVlsKmypehHdGE1Lx-Z_cqmCjNqnAz8_XVZxVOAMs5v3eWxXFriAN7KRMVSs__tdKMIXCPL2utdLwyYL4XJ-fjMyHQR4AVlRK8pc5ACCjnFHvQnqNgUFYrKInIF9irLnp3Y.QgEx1HP9HlIlDgrthdtSMIm0lGDkenWTWj1irbmhtn4&dib_tag=se&keywords=candi+cat+diamond+art&qid=1769298265&sprefix=candi+cat+diamond+art%2Caps%2C100&sr=8-6
        - Fourthwall: https://devicat-shop.fourthwall.com
excerpt_separator: <!--card-->